feat: add type definition
radenkovic/feathers-debugger-service pull request #8
Opened 2020-10-03 11:17 UTC by bwgjoseph

Added type definition for this project, closes #6 

I have tested with ts/js project, and both looking fine. As this my first time adding for type definition, I hope I didn't miss out anything.

If this does gets accepted, do consider adding `topic` and `label` for [hacktoberfest](https://hacktoberfest.digitalocean.com/hacktoberfest-update) so it counts towards the contribution

2020-10-05 08:53 UTC, radenkovic requested changes
This looks great so far, only two minor changes and we are good to go! Thanks for the PR!

2020-10-05 08:53 UTC, radenkovic commented on types/index.d.ts
> +  ui: boolean;
this one is optional

2020-10-05 08:53 UTC, radenkovic commented on types/index.d.ts
> +  publicUrl: string;
this one is optional too

2020-10-05 15:46 UTC, bwgjoseph commented
Ah, yes. Thanks for that.

Changes are all done

2020-10-07 19:01 UTC, radenkovic commented
Perfect, merging, thank you!

2020-10-07 19:01 UTC, merged